# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from executive/Waypoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Waypoint(genpy.Message):
  _md5sum = "9a56c7b6ec935796a4257037b2c62ee0"
  _type = "executive/Waypoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 latitude
float32 longitude
int32 waypoint_number
bool is_last"""
  __slots__ = ['latitude','longitude','waypoint_number','is_last']
  _slot_types = ['float32','float32','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,waypoint_number,is_last

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Waypoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.waypoint_number is None:
        self.waypoint_number = 0
      if self.is_last is None:
        self.is_last = False
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.waypoint_number = 0
      self.is_last = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2fiB().pack(_x.latitude, _x.longitude, _x.waypoint_number, _x.is_last))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.latitude, _x.longitude, _x.waypoint_number, _x.is_last,) = _get_struct_2fiB().unpack(str[start:end])
      self.is_last = bool(self.is_last)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2fiB().pack(_x.latitude, _x.longitude, _x.waypoint_number, _x.is_last))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.latitude, _x.longitude, _x.waypoint_number, _x.is_last,) = _get_struct_2fiB().unpack(str[start:end])
      self.is_last = bool(self.is_last)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fiB = None
def _get_struct_2fiB():
    global _struct_2fiB
    if _struct_2fiB is None:
        _struct_2fiB = struct.Struct("<2fiB")
    return _struct_2fiB
