// Generated by gencpp from file compass/CompassBearing.msg
// DO NOT EDIT!


#ifndef COMPASS_MESSAGE_COMPASSBEARING_H
#define COMPASS_MESSAGE_COMPASSBEARING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace compass
{
template <class ContainerAllocator>
struct CompassBearing_
{
  typedef CompassBearing_<ContainerAllocator> Type;

  CompassBearing_()
    : bearing(0.0)  {
    }
  CompassBearing_(const ContainerAllocator& _alloc)
    : bearing(0.0)  {
  (void)_alloc;
    }



   typedef float _bearing_type;
  _bearing_type bearing;





  typedef boost::shared_ptr< ::compass::CompassBearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compass::CompassBearing_<ContainerAllocator> const> ConstPtr;

}; // struct CompassBearing_

typedef ::compass::CompassBearing_<std::allocator<void> > CompassBearing;

typedef boost::shared_ptr< ::compass::CompassBearing > CompassBearingPtr;
typedef boost::shared_ptr< ::compass::CompassBearing const> CompassBearingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::compass::CompassBearing_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::compass::CompassBearing_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::compass::CompassBearing_<ContainerAllocator1> & lhs, const ::compass::CompassBearing_<ContainerAllocator2> & rhs)
{
  return lhs.bearing == rhs.bearing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::compass::CompassBearing_<ContainerAllocator1> & lhs, const ::compass::CompassBearing_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace compass

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::compass::CompassBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::compass::CompassBearing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::compass::CompassBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::compass::CompassBearing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::compass::CompassBearing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::compass::CompassBearing_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::compass::CompassBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d288057649bbf117ba71f807d147816d";
  }

  static const char* value(const ::compass::CompassBearing_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd288057649bbf117ULL;
  static const uint64_t static_value2 = 0xba71f807d147816dULL;
};

template<class ContainerAllocator>
struct DataType< ::compass::CompassBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "compass/CompassBearing";
  }

  static const char* value(const ::compass::CompassBearing_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::compass::CompassBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 bearing\n"
;
  }

  static const char* value(const ::compass::CompassBearing_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::compass::CompassBearing_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CompassBearing_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::compass::CompassBearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::compass::CompassBearing_<ContainerAllocator>& v)
  {
    s << indent << "bearing: ";
    Printer<float>::stream(s, indent + "  ", v.bearing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPASS_MESSAGE_COMPASSBEARING_H
