# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from collision_detection/CollisionInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import collision_detection.msg

class CollisionInfo(genpy.Message):
  _md5sum = "a174fa88f0c00f2e81e61d98593bf57f"
  _type = "collision_detection/CollisionInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Obstacle left
Obstacle center
Obstacle right
================================================================================
MSG: collision_detection/Obstacle
float64 distance
float64 priority"""
  __slots__ = ['left','center','right']
  _slot_types = ['collision_detection/Obstacle','collision_detection/Obstacle','collision_detection/Obstacle']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left,center,right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CollisionInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left is None:
        self.left = collision_detection.msg.Obstacle()
      if self.center is None:
        self.center = collision_detection.msg.Obstacle()
      if self.right is None:
        self.right = collision_detection.msg.Obstacle()
    else:
      self.left = collision_detection.msg.Obstacle()
      self.center = collision_detection.msg.Obstacle()
      self.right = collision_detection.msg.Obstacle()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.left.distance, _x.left.priority, _x.center.distance, _x.center.priority, _x.right.distance, _x.right.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.left is None:
        self.left = collision_detection.msg.Obstacle()
      if self.center is None:
        self.center = collision_detection.msg.Obstacle()
      if self.right is None:
        self.right = collision_detection.msg.Obstacle()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.left.distance, _x.left.priority, _x.center.distance, _x.center.priority, _x.right.distance, _x.right.priority,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.left.distance, _x.left.priority, _x.center.distance, _x.center.priority, _x.right.distance, _x.right.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.left is None:
        self.left = collision_detection.msg.Obstacle()
      if self.center is None:
        self.center = collision_detection.msg.Obstacle()
      if self.right is None:
        self.right = collision_detection.msg.Obstacle()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.left.distance, _x.left.priority, _x.center.distance, _x.center.priority, _x.right.distance, _x.right.priority,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
