// Generated by gencpp from file navigation/MotorSpeed.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_MOTORSPEED_H
#define NAVIGATION_MESSAGE_MOTORSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct MotorSpeed_
{
  typedef MotorSpeed_<ContainerAllocator> Type;

  MotorSpeed_()
    : left_speed(0)
    , right_speed(0)  {
    }
  MotorSpeed_(const ContainerAllocator& _alloc)
    : left_speed(0)
    , right_speed(0)  {
  (void)_alloc;
    }



   typedef int8_t _left_speed_type;
  _left_speed_type left_speed;

   typedef int8_t _right_speed_type;
  _right_speed_type right_speed;





  typedef boost::shared_ptr< ::navigation::MotorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::MotorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeed_

typedef ::navigation::MotorSpeed_<std::allocator<void> > MotorSpeed;

typedef boost::shared_ptr< ::navigation::MotorSpeed > MotorSpeedPtr;
typedef boost::shared_ptr< ::navigation::MotorSpeed const> MotorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::MotorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::MotorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::MotorSpeed_<ContainerAllocator1> & lhs, const ::navigation::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.left_speed == rhs.left_speed &&
    lhs.right_speed == rhs.right_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::MotorSpeed_<ContainerAllocator1> & lhs, const ::navigation::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::MotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::MotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "484d956611ab81479ec19d6a5dc9c74a";
  }

  static const char* value(const ::navigation::MotorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x484d956611ab8147ULL;
  static const uint64_t static_value2 = 0x9ec19d6a5dc9c74aULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/MotorSpeed";
  }

  static const char* value(const ::navigation::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 left_speed\n"
"int8 right_speed\n"
;
  }

  static const char* value(const ::navigation::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::MotorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_speed);
      stream.next(m.right_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::MotorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::MotorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "left_speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left_speed);
    s << indent << "right_speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_MOTORSPEED_H
