// Generated by gencpp from file navigation/WaypointReached.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_WAYPOINTREACHED_H
#define NAVIGATION_MESSAGE_WAYPOINTREACHED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct WaypointReached_
{
  typedef WaypointReached_<ContainerAllocator> Type;

  WaypointReached_()
    : latitude(0.0)
    , longitude(0.0)
    , waypoint_number(0)  {
    }
  WaypointReached_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , waypoint_number(0)  {
  (void)_alloc;
    }



   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef int32_t _waypoint_number_type;
  _waypoint_number_type waypoint_number;





  typedef boost::shared_ptr< ::navigation::WaypointReached_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::WaypointReached_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointReached_

typedef ::navigation::WaypointReached_<std::allocator<void> > WaypointReached;

typedef boost::shared_ptr< ::navigation::WaypointReached > WaypointReachedPtr;
typedef boost::shared_ptr< ::navigation::WaypointReached const> WaypointReachedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::WaypointReached_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::WaypointReached_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::WaypointReached_<ContainerAllocator1> & lhs, const ::navigation::WaypointReached_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.waypoint_number == rhs.waypoint_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::WaypointReached_<ContainerAllocator1> & lhs, const ::navigation::WaypointReached_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::WaypointReached_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::WaypointReached_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::WaypointReached_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::WaypointReached_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::WaypointReached_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::WaypointReached_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::WaypointReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae1ddeee9499ffebaac8e88a62b4a24e";
  }

  static const char* value(const ::navigation::WaypointReached_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae1ddeee9499ffebULL;
  static const uint64_t static_value2 = 0xaac8e88a62b4a24eULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::WaypointReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/WaypointReached";
  }

  static const char* value(const ::navigation::WaypointReached_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::WaypointReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 latitude\n"
"float32 longitude\n"
"int32 waypoint_number\n"
;
  }

  static const char* value(const ::navigation::WaypointReached_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::WaypointReached_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.waypoint_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointReached_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::WaypointReached_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::WaypointReached_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "waypoint_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_WAYPOINTREACHED_H
