// Generated by gencpp from file distance_sensor/Distance.msg
// DO NOT EDIT!


#ifndef DISTANCE_SENSOR_MESSAGE_DISTANCE_H
#define DISTANCE_SENSOR_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distance_sensor
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : distance_front(0.0)
    , distance_left(0.0)
    , distance_right(0.0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : distance_front(0.0)
    , distance_left(0.0)
    , distance_right(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_front_type;
  _distance_front_type distance_front;

   typedef double _distance_left_type;
  _distance_left_type distance_left;

   typedef double _distance_right_type;
  _distance_right_type distance_right;





  typedef boost::shared_ptr< ::distance_sensor::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_sensor::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::distance_sensor::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::distance_sensor::Distance > DistancePtr;
typedef boost::shared_ptr< ::distance_sensor::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distance_sensor::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distance_sensor::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distance_sensor::Distance_<ContainerAllocator1> & lhs, const ::distance_sensor::Distance_<ContainerAllocator2> & rhs)
{
  return lhs.distance_front == rhs.distance_front &&
    lhs.distance_left == rhs.distance_left &&
    lhs.distance_right == rhs.distance_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distance_sensor::Distance_<ContainerAllocator1> & lhs, const ::distance_sensor::Distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distance_sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distance_sensor::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distance_sensor::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_sensor::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_sensor::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_sensor::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_sensor::Distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distance_sensor::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cdc47dfe636ccbe1ecabbc8b3b2dd90";
  }

  static const char* value(const ::distance_sensor::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cdc47dfe636ccbeULL;
  static const uint64_t static_value2 = 0x1ecabbc8b3b2dd90ULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_sensor::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distance_sensor/Distance";
  }

  static const char* value(const ::distance_sensor::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distance_sensor::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance_front\n"
"float64 distance_left\n"
"float64 distance_right\n"
;
  }

  static const char* value(const ::distance_sensor::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distance_sensor::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_front);
      stream.next(m.distance_left);
      stream.next(m.distance_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_sensor::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distance_sensor::Distance_<ContainerAllocator>& v)
  {
    s << indent << "distance_front: ";
    Printer<double>::stream(s, indent + "  ", v.distance_front);
    s << indent << "distance_left: ";
    Printer<double>::stream(s, indent + "  ", v.distance_left);
    s << indent << "distance_right: ";
    Printer<double>::stream(s, indent + "  ", v.distance_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTANCE_SENSOR_MESSAGE_DISTANCE_H
